
# Basis-Image
FROM python:3.10

# Arbeitsverzeichnis setzen
WORKDIR /app

# Abhängigkeiten installieren
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Code kopieren
COPY . .

# Startbefehl
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8002"]
EXPOSE 8002

